version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./static:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      # - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      # - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      # - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      # - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}

    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  fastapi-app:
    build:
      context: ./fastapi-app
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi-app:/fastapi-app
    env_file:
      - ./fastapi-app/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  dev-db-data:
