global:
  scrape_interval: 15s # 메트릭을 15초마다 수집

scrape_configs:
  # Django 애플리케이션의 /metrics 엔드포인트에서 메트릭 수집
  - job_name: "app"
    scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-wisp.site:443"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
