# Generated by Django 5.1.8 on 2025-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_folder_deleted_at_folder_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='메모를 작성해주세요.(마크다운 지원)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='무제', max_length=255),
        ),
    ]
