# Generated by Django 5.1.8 on 2025-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
