# Generated by Django 5.1.8 on 2025-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default={'content': [{'content': [{'text': '내용을 입력하세요.', 'type': 'text'}], 'type': 'paragraph'}, {'type': 'paragraph'}], 'type': 'doc'}),
        ),
    ]
