# Generated by Django 5.1.8 on 2025-05-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_alter_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='likes_count',
        ),
    ]
