# Generated by Django 5.1.8 on 2025-05-15 06:44

import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_remove_note_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default=note.models.default_tiptap_doc),
        ),
    ]
