# Generated by Django 5.1.9 on 2025-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_alter_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='note',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
