---
name: Checks

on:
  push:
    branches:
      - main # main 브랜치만

jobs:
  test-lint: # job 이름(이름 수정 가능)
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout # github -> ubuntu로 코드 가져오기 (로컬이 아니기때문에 가져와야함)
        uses: actions/checkout@v3

      - name: Test
        working-directory: ./backend
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && pytest"

      - name: Lint
        working-directory: ./backend
        run: docker compose run --rm app sh -c "flake8"
